apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbm-deploy
  labels:
    app: my-k8s-deployments
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cbm
  template:
    metadata:
      labels:
        project: cbm
    spec:
      containers:
      - name: app
        image: tomcat:8.5.38
        ports:
        - containerPort: 8080