apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbm-deployment
  labels:
    app: my-k8s-deployment
    enviroment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      project: cbm
  template:
    metadata:
      labels:
        project: cbm
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cbm-service
  labels:
    env: prod
    owner: IlyaShevchenko
spec:
  selector:
    project: cbm
  ports:
  - name: app-listener
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer