apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbm-deploy
  labels:
    app: my-k8s-deployment
    enviroment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      project: cbm
  template:
    metadata:
      labels:
        project: cbm
    spec:
      containers:
      - name: app
        image: tomcat:8.5.38
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cbm-svc
  labels:
    env: prod
    owner: IlyaShevchenko
spec:
	type: LoadBalancer
  selector:
    project: cbm
  ports:
  - name: app-listener
    protocol: TCP
    port: 8888
    targetPort: 8080