apiVersion: apps/v1
kind: Deployment
metadata:
	name: cbm-deployment
spec:
	replicas: 1
	template:
		metadata:
			labels:
				run: cbm
	spec:
		containers:
			- name: cbm
			  image: golang:1.16.3
			  ports:
				  – containerPort: 8888