apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbm-deploy
  labels:
    app: my-k8s-deployments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cbm
  template:
    metadata:
      labels:
        app: cbm
    spec:
      containers:
      - name: app
        image: tomcat:8.5.38
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cbm-svc
  labels:
    env: prod
    owner: IlyaShevchenko
spec:
  type: LoadBalancer
  selector:
    app: cbm
  ports:
  - name: app-listener
    protocol: TCP
    port: 8888
    targetPort: 8080