apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbm-deployment
  labels:
    app: cbm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cbm
  template:
    metadata:
      labels:
        app: cbm
    spec:
      containers:
      - name: cbm
        image: golang:1.16.3
        ports:
        - containerPort: 80
