# will create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbm-deployment
  labels:
    app: my-k8s-deployment
    enviroment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      project: cbm
  template:
    metadata:
      labels:
        project: cbm  # Service will look for those Pods Labels!!!
    spec:
      containers:
      - name: app
        image: golang:1.16.3
        tty: true
        ports:
        - containerPort: 80
      - name: mongo
        image: mongo:4
        ports:
        - containerPort: 27017
        command: ["/bin/sh"]
        args: ["-c", "mongod --replSet=rs0"]

---
# will create service
apiVersion: v1
kind: Service
metadata:
  name: cbm-service
  labels:
    env: prod
    owner: IlyaShevchenko
spec:
  selector:
    project: cbm  # Selecting PODS with those Labels
  ports:
  - name: app-listener
    protocol: TCP
    port: 80        # Port on LoadBalancer
    targetPort: 80  # Port on POD
  type: LoadBalancer